# Directories
basedir: ".."
refdir: "ref/"
rawdir: "rawData/"

# Reference files
reference:
    GRCh38:
#        chr1: ftp://ftp.ensembl.org/pub/release-87/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.1.fa.gz
        chr22: ftp://ftp.ensembl.org/pub/release-87/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.22.fa.gz
        MT: ftp://ftp.ensembl.org/pub/release-87/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.MT.fa.gz


# ChIPsim
ChIPsim:
    cmd: "Rscript scripts/simulate_reads.R"
    EF: 5
    nReps: 2


# bowtie2-build parameters
bowtie2-build:
    cmd: "bowtie2-build"


# bowtie2 parameters
bowtie2:
    cmd: "bowtie2"
    in_fmt: "-q"
    phred: "--phred33"
    maxins: 500
    mismatch: 0
    threads: 6
